---
os: linux
dist: bionic

addons:
  ssh_known_hosts: ${DEPLOY_HOST}

language: node_js
node_js:
  - "lts/*"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb
  - npm install

script:
  - hugo version
  - gulp

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.68.3

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
