---
os: linux
dist: bionic

addons:
  ssh_known_hosts: ${DEPLOY_HOST}

language: node_js
node_js:
  - lts/*

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb
  - npm install

script:
  - hugo version
  - gulp

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.68.3
    - secure: P6d7E7/VL9oQbYrmicOruvDPfhn9yIyT6rEgDnBOHa9wpmX3DRaidUPlvMpz/Z7LNNdGY2yM+vjJ5OvPC8xeLxo3rKFcl7fG3WQjMXP2/iXXhbl/Rar0rwqY+tlDsKx3GraCBdIeR7sQ98fMZA+6zCJP4mguxiCxWJBit7m3gJE+N1pJAKHGSP29g7GsXb2OmY7HZwlGm6zo6syFZS+fEfjVy+K4fLYfNk6Xl3AWSIhEUvfIPZ1rieCm4ySjUzwBhDX1FVnPbyRPRt2v0zx8uEGR7+2jy7p1r3KTXtm0DoaBWhuYZAqzVQAjHDvZXfaVpVxgmbRp57124mqJ6t0TBiBJmHqnscvpeF+gy1EtgEv1kHgxOZLpcg/eT50u8M/PrVvPgmC1WqgrxVubesQE4Polfdv5orzQ+jzWBFfTNwrfHBXvM+GZ68Ax59B92Gdx8yL0T9zhn+mY3ndcsa8f0bVShK9OTU8z9i9dznGerxqHXjYtuXE2f+q/hN+cDsNik0VxCk21o9k0WWfZcfRQzrur6DYumXo+JvSOhZLEdL/vGU7uEGsIk+OW8U/Y0+Q8VG9JSvhIjMyIBkhVh5S/qanAFq4m67zy/nZrC75o3dSgA3cVtJ33Y456xTrrjRGBKg+GQ8vqoaRoirQF4KW/O/vovfj1PpHTrMlcMPaudTw=
    - secure: im0dL4DvHwtd31DcyLsorc0K59A4QmnpxpQwHrvVjAhiWOKAAYLIafSWJLyQUAISsbmdLxpY9WjJaIEi4hFPYHF85MSlKNUiDX0e0Q0hbDuy330Bt7pXpRADKkwjExuDdGCielBm9GnZHT/NXjpz2wRMm4bFQSWPkwc1NTW7Igy05SIaeh34Ie0EQ1lIAPXsm/LuUp6P9MIP3FpxQReiqk+xlNlCTTkV+MKoqaPy4O39zDmqBK/MO/jqpEmlqaNclLFrixGH2GmSQUzrYxkqQr0B1cm54V6IUoqPtF9hbB05zjb5hn9ii5EqwpdfuA3isA0+KNx0e7t9oxTwbMwSsBVfOJ1kWMhcQU9MR/uEc+yII1ozKKHNYxba3OnODTC1vihIrXT7XXBThTodxhF2tPffh8WCQ0mmFFSxkLr6ytuLW55alZt+X2ryJQWlIc4xJmsQa3elztcyZnLnuGU8/peMJt0kHF6qbtCsgmb3nC5XfCEj3v+9mRElba5aftSMoTxb1oThSQ5rvCgLUTeW3md1uXIDvCoSp9DyLCDKQLkd2rT5n+z4++ST26Ywh8r0KmPn/bA13vgwuLHYmtvIgrpu9uPHVi1Tbe62RiS3SpRhmzrTyfKGAm5v9zbsfi8yXT8B1nnC+WbKIcoX+THfvCOWFks4GiVIMPVJPHwxm0c=
    - secure: qRd6ZJ13qeeVtByEg4i1mGmmZk9sbd0XlhpoGlSWgFWc9cAOb2OMgyCHX0U6wVqJ0aQ0WLKPLy5Ym4vGn5GhbAcA7HrLFiTqrxoaxHfHhonbE8Rw5m5pY8d3HPHe/CsRynfl02G0pZ9C82mnZeooTez6MLUEbYv92Y1iGbaLXzU/hAxvUSEWQgi252/QnmGLCjBf9Jd+xZd67UYTg1c+lixRnh27pXFZBPNXUzF8q/RnR8uUPJKVR8IVAKH6Jp20hs5358GLMkxn8mRcs0D9ClgVinoxq60nElMKxsCOMyheX1ia6A4bUFf11tPZ2f6de1nYoeped3N5cfpz1xKwlSInbRK2b0sKJI/0Ere2t8xFDybaBd5jIYru4V7pCjWfbolPcTA8uwoL+ILdNEZpXJmgweW4qND6bQP7hRvlM06DKchGTufilWirvcZIqNJLc4xSTy6IXYXAmWeLeWpvJ/p/iUlY1l9nKOS36lPVFGuF2otDc3qax1EXPrODft/Brr23ng+s4ycoJXbAMGfH6E9WsRD+qXTCBD4cdOE1GwvmJyTmmiV4xdrqC7eKEcl/ER68nBOGv5FCnPkR5Bfl3DykLWS8NpuQgeqNDvcHpNboXCCaAKX0s+LziAw+0Sb25kG6SprysVeH4+cgnL4Z7yQ77m12j3bGfwTtRZmVyQ0=

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
