baseURL: 'https://moodletoolguide.net/'
languageCode: en-us

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage: fr

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: true

disableKinds:
- taxonomy
- taxonomyTerm

outputFormats:
  CSS:
    path: '/css/'
    baseName: 'i18n'

params:
  author: Nicolas Martignoni
  githubUsername: 'martignoni'
  accent: '#f98012'
  showBorder: true
  backgroundColor: white
  favicon: 'img/moodle-logo-icon.png'
  matomoAnalytics:
    siteid: 4
    matomoroot: "stats.martignoni.net" # Do not add slashes
  menu:
    icon:
      - url: 'mailto:me@example.com'
        name: envelope-o
        weight: 1
      - url: 'https://github.com/martignoni/moodle-tool-guide'
        name: github
        weight: 2
  #     - url: 'https://twitter.com/nmartignoni/'
  #       name: twitter
  #       weight: 3
  #     - url: 'https://www.linkedin.com/in/nicolasmartignoni/'
  #       name: linkedin
  #       weight: 4
  #     - url: 'https://stackoverflow.com/users/11589458/nicolas-martignoni'
  #       name: stack-overflow
  #       weight: 5

languages:
  en:
    languageName: English
    title: Moodle Tool Guide
    slogan: Moodle Tool Guide for teachers and educators
    description: 'Moodle Tool Guide: A Quick Reference Guide for teachers and educators to use Moodle version 3 and later.'
    date_format: January 2, 2006
    contentDir: content/en
    copyright: 'Provided by [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – This work is licensed under a [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) License.'
    weight: 1
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: About
          weight: 2
      icon:
        # - url: 'mailto:nicolas@martignoni.net'
        #  name: envelope-o
        #  weight: 1
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  fr:
    languageName: Français
    title: Guide des outils Moodle
    slogan: Guide des outils Moodle pour enseignant·es et formateur·trices
    description: "Guide des outils Moodle : un aide-mémoire pour l'utilisation de Moodle version 3 et ultérieures, destiné aux enseignantes et enseignants et aux formatrices et formateurs."
    contentDir: content/fr
    date_format: 2 January 2006
    copyright: 'Offert par [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Ce site web est publié sous licence [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).'
    weight: 2
    menu:
      main:
        - url: /
          name: Accueil
          weight: 1
        - url: /about/
          name: À propos
          weight: 1
      icon:
        # - url: 'mailto:nicolas@martignoni.net'
        #  name: envelope-o
        #  weight: 1
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2
